### ISSUE TITLE
The face detection model and licence plate detection model are not working with TIM-VX backend with opencv 4.8

### ISSUE THREAD

**Issue by fengyuentau** [opencv/opencv_zoo#198]
This problem is found at https://github.com/opencv/opencv_zoo/pull/190#discussion_r1257832066. A possible quick solution is we can try updating models to bypass this problem.

Failed log:

```
E [/home/opencv-cn/Workspace/opencv/build/release-4.8.0/3rdparty/libtim-vx/TIM-VX-1d9c7ab941b3d8d9c4d28d80058402725731e3d6/src/tim/vx/internal/src/utils/vsi_nn_dtype_util.c:vsi_nn_QuantCheck:429]input_scale[1.000000000000] * weight_scale[0.010799630545] != bias_scale[0.000318158010]
E [/home/opencv-cn/Workspace/opencv/build/release-4.8.0/3rdparty/libtim-vx/TIM-VX-1d9c7ab941b3d8d9c4d28d80058402725731e3d6/src/tim/vx/internal/src/vsi_nn_graph.c:setup_node:481]Check node[4] CONV2D fail
Traceback (most recent call last):
  File "benchmark.py", line 227, in <module>
    benchmark.run(model)
  File "benchmark.py", line 132, in run
    self._benchmark_results[str(size)][filename] = self._metric.forward(model, *data[1:])
  File "/home/opencv-cn/Workspace/opencv/opencv_zoo/benchmark/utils/metrics/detection.py", line 21, in forward
    model.infer(img)
  File "/home/opencv-cn/Workspace/opencv/opencv_zoo/models/face_detection_yunet/yunet.py", line 54, in infer
    faces = self._model.detect(image)
cv2.error: OpenCV(4.8.0) /home/opencv-cn/Workspace/opencv/opencv/modules/dnn/src/op_timvx.cpp:513: error: (-5:Bad argument)  Fail to compile TimVX graph! in function 'forward'


E [/home/opencv-cn/Workspace/opencv/build/release-4.8.0/3rdparty/libtim-vx/TIM-VX-1d9c7ab941b3d8d9c4d28d80058402725731e3d6/src/tim/vx/internal/src/utils/vsi_nn_dtype_util.c:vsi_nn_QuantCheck:429]input_scale[1.000000000000] * weight_scale[0.003745428752] != bias_scale[0.000043810331]
E [/home/opencv-cn/Workspace/opencv/build/release-4.8.0/3rdparty/libtim-vx/TIM-VX-1d9c7ab941b3d8d9c4d28d80058402725731e3d6/src/tim/vx/internal/src/vsi_nn_graph.c:setup_node:481]Check node[4] CONV2D fail
Traceback (most recent call last):
  File "benchmark.py", line 227, in <module>
    benchmark.run(model)
  File "benchmark.py", line 132, in run
    self._benchmark_results[str(size)][filename] = self._metric.forward(model, *data[1:])
  File "/home/opencv-cn/Workspace/opencv/opencv_zoo/benchmark/utils/metrics/detection.py", line 21, in forward
    model.infer(img)
  File "/home/opencv-cn/Workspace/opencv/opencv_zoo/models/license_plate_detection_yunet/lpd_yunet.py", line 54, in infer
    outputBlob = self.model.forward(self.output_names)
cv2.error: OpenCV(4.8.0) /home/opencv-cn/Workspace/opencv/opencv/modules/dnn/src/op_timvx.cpp:513: error: (-5:Bad argument)  Fail to compile TimVX graph! in function 'forward'
```
