### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'TrackerVit_Params'

### ISSUE THREAD

**Issue by arielkantorovich** [opencv/opencv_zoo#216]
Hi,
First Thank you for the great repo, I tried to run the VitTracker example.

**environment**
Ubuntu 16.04 WSL
Python 3.9.18 conda venv

I follow your instructions (README.md), when I run:
`python demo.py --input exam.mp4`
I get this error:
```
  File "/mnt/c/Users/arielka/PycharmProjects/VitTracker/opencv_zoo/models/object_tracking_vittrack/demo.py", line 69, in <module>    
    model = VitTrack(                                                                                                                
  File "/mnt/c/Users/arielka/PycharmProjects/VitTracker/opencv_zoo/models/object_tracking_vittrack/vittrack.py", line 13, in __init__
    self.params = cv.TrackerVit_Params()                                                                                             
AttributeError: module 'cv2' has no attribute 'TrackerVit_Params'
```
It looks like in the opencv library cv.TrackerVit not exist.
I will be happy to help.
Thank you :)

**Comment by fengyuentau** [comment]
Hello!

You need to compile lastest opencv from source to have this API `cv.TrackerVit`. Or you can wait a month or two for the release of opencv 4.9.0 which comes with this API pre-built.

**Comment by arielkantorovich** [comment]
Ok, thank you for answer, for now there is option to use Dasiam Tracker which version of git lfs I need to use?

**Comment by fengyuentau** [comment]
DasiamRPN is removed since b0fe2136b6695ac8c0f095382cdb051bd172963d. You can go back to when it still exists with

```
git checkout fef72f8fa7c52eaf116d3df358d24e6e959ada0e
```

---

Also note that VitTrack outperforms DaSiamRPN in terms of speed and file size. VitTrack worths a build from source.

| Model | File size (MB) | Speed on Raspberry 4 CPU (ms) |
| - | - | - |
| VitTrack | 0.698 | 90.49 |
| DaSiamRPN | 154.3 | 564.90 |

**Comment by arielkantorovich** [comment]
I will be very happy to your help,
Reminder, I work on WSL ubuntu 16.04 python version 3.9 with conda.
I build OpenCV from source by these steps:
`sudo apt-get update
sudo apt-get install build-essential cmake git pkg-config libgtk-3-dev \
                     libavcodec-dev libavformat-dev libswscale-dev \
                     libv4l-dev libxvidcore-dev libx264-dev \
                     libjpeg-dev libpng-dev libtiff-dev \
                     gfortran openexr libatlas-base-dev \
                     python3-dev python3-numpy libtbb2 libtbb-dev \
                     libdc1394-22-dev`


`git clone https://github.com/opencv/opencv.git
git clone https://github.com/opencv/opencv_contrib.git`

`cd opencv
mkdir build
cd build

cmake -D CMAKE_BUILD_TYPE=RELEASE \
      -D CMAKE_INSTALL_PREFIX=/usr/local \
      -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules \
      -D OPENCV_ENABLE_NONFREE=ON \
      -D PYTHON3_EXECUTABLE=$(which python3) \
      -D BUILD_opencv_python3=ON \
      -D INSTALL_PYTHON_EXAMPLES=ON \
      -D INSTALL_C_EXAMPLES=OFF \
      -D BUILD_EXAMPLES=ON ..

make -j8  # Adjust the number according to the number of CPU cores`

`sudo make install
sudo ldconfig`

Everything succeeded and I did not get any error but still, it's not find the API cv.VitTrack.
What I miss?

**Comment by fengyuentau** [comment]
Most probably you did not install the compiled python package. Make sure you uninstall the old one, then install the new one:

```bash
python3 -m pip list # if package name is opencv-python, it means you are still using the release version, which does not have vittrack
python3 -m pip uninstall opencv-python

python3 -m pip install /path/to/opencv/build/python_loader
python3 -m pip list # package name should be opencv, which is the version you just compiled
```

**Comment by arielkantorovich** [comment]
Thank you so much for your help, Now I get an error in line 86
`{error}OpenCV(4.8.0-dev) /mnt/c/Users/arielka/PycharmProjects/VitTracker/opencv/modules/highgui/src/window_gtk.cpp:638: error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'
`
When I run 
`roi = cv.selectROI('vitTrack Demo', first_frame_copy)`

maybe the reason is that I want on WSL?
How I can solve this?

**Comment by fengyuentau** [comment]
You need a GUI for your WSL https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps. Most probably you also need to google how to access camera inside WSL.

**Comment by fengyuentau** [comment]
This goes too far from opencv related content. If you can do this all over again on your native platform, not WSL, you will smoothly get what you want.
